### ISSUE TITLE
How to load css file?

### ISSUE THREAD

**Issue by alanyangbo** [dpjudas/UICore#10]

**Comment by dpjudas** [comment]
**Short answer:**
You can't. You have to call style()->set("css properties here") on a view to set CSS properties.

**Long answer:**
I'm currently experimenting with a new file format for describing views, including their CSS properties. You can find some .view files in the ViewCompiler example folder that shows how it looks right now (remember: still work in progress!). The basic idea I'm testing out is whether I can combine CSS and typical HTML tree information into a single description focused around inherited views. The compiler reads one or more of those files and generates C++ header files.

If you'd like me to hurry up on finishing this please let me know. :)

I also have some old code that can parse CSS files and apply them to a tree using the selectors. If there's enough interest in it I can add it as a class to UICore. But personally my interest is limited due to never having seen a CSS file that didn't turn into an unreadable mess.
